from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

out = 'Laporan_Pengujian_Quiz_Pengupil.pdf'
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='Small', parent=styles['BodyText'], fontSize=8, leading=10))
doc = SimpleDocTemplate(out, pagesize=A4, rightMargin=14*mm, leftMargin=14*mm, topMargin=14*mm, bottomMargin=14*mm)
story = [Paragraph('Laporan Pengujian Modul Login dan Register', styles['Title']),
         Paragraph('David Sam Limbong | III RPLK | 2322101894', styles['Normal']),
         Paragraph('Aplikasi: quiz-pengupil (PHP + MySQL + mysqli)', styles['Normal']), Spacer(1, 8)]
story += [Paragraph('1. Pendahuluan', styles['Heading2']), Paragraph('Pengujian mencakup login.php dan register.php. Tujuannya memverifikasi alur sukses, validasi input, keamanan SQL injection/XSS, serta konsistensi session dan data database.', styles['BodyText'])]
story += [Paragraph('2. Metodologi', styles['Heading2']), Paragraph('Selenium WebDriver mengisi form melalui browser seperti pengguna nyata. Fixture pytest mereset tabel users dan menanam user bcrypt testuser/Test123! sebelum tiap skenario. Assertion memeriksa URL, pesan UI, dan isi database melalui mysql-connector-python. Screenshot kegagalan serta JUnit XML diunggah sebagai artifact CI.', styles['BodyText'])]
rows = [['ID','Modul','Skenario','Expected output','Status'],
['LG-01','Login','Kredensial valid','Redirect index.php','Pass/CI'],['LG-02','Login','Username tidak terdaftar','Pesan gagal, tetap login','Pass/CI'],['LG-03','Login','Password salah','Pesan autentikasi','XFAIL: bug error kosong'],['LG-04','Login','Username kosong','Pesan data kosong','Pass/CI'],['LG-05','Login','Password kosong','Pesan data kosong','Pass/CI'],['LG-06','Login','Keduanya kosong','Pesan data kosong','Pass/CI'],['LG-07','Login','SQL injection username','Login ditolak','Pass/CI'],['LG-08','Login','Session aktif','Auto-redirect index.php','Pass/CI'],['RG-01','Register','Semua field valid','Insert + redirect','XFAIL terkait nama'],['RG-02','Register','Username duplikat','Pesan sudah terdaftar','Pass/CI'],['RG-03','Register','Password berbeda','Pesan tidak sama','Pass/CI'],['RG-04','Register','Field kosong','Pesan data kosong','Pass/CI'],['RG-05','Register','Email invalid','Server menolak','XFAIL: validasi email tidak ada'],['RG-06','Register','Verifikasi kolom name','Nama tersimpan utuh','XFAIL: $nama undefined'],['RG-07','Register','XSS pada nama','Tidak dieksekusi/di-escape','Risiko: escaping output belum ada']]
t = Table([[Paragraph(str(c), styles['Small']) for c in r] for r in rows], colWidths=[13*mm,18*mm,52*mm,58*mm,28*mm], repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#1f4e79')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.25,colors.grey),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#eef4fa')])]))
story += [Paragraph('3. Tabel Testcase', styles['Heading2']), Paragraph('Dokumen Word terlampir memperluas rancangan menjadi 47 skenario (17 login dan 30 register). Tabel berikut memuat testcase inti.', styles['BodyText']), t, PageBreak()]
story += [Paragraph('4. Implementasi', styles['Heading2']), Paragraph('File utama: tests/conftest.py (driver dan fixture), tests/db_stub.py (reset/seed/query), tests/test_login.py, tests/test_register.py, requirements.txt, serta .github/workflows/selenium-ci.yml. Pipeline menjalankan MySQL service healthcheck, import SQL, PHP built-in server, Chrome headless, pytest -v, dan upload artifact.', styles['BodyText']), Spacer(1,8), Paragraph('Contoh eksekusi:', styles['Heading3']), Paragraph('pytest tests/ -v --junitxml=artifacts/report.xml', styles['Code']), Spacer(1,8), Paragraph('5. Bukti Validasi', styles['Heading2']), Paragraph('Validasi lokal berhasil: PHP login.php dan register.php lulus php -l; seluruh 15 testcase berhasil dikoleksi pytest; database XAMPP berhasil dibuat, diimpor, di-reset, dan di-seed. Eksekusi UI penuh memerlukan ChromeDriver yang tersedia. CI memasang Chrome dan ChromeDriver secara otomatis.', styles['BodyText']), Spacer(1,8), Paragraph('6. Kesimpulan dan Temuan Bug', styles['Heading2']), Paragraph('Ditemukan: password salah tidak mengisi $error; query register memakai $nama bukan $name; email tidak divalidasi server; guard register memeriksa session key user bukan username; dan output nama belum di-escape sehingga berisiko XSS ketika dirender.', styles['BodyText']), Spacer(1,8), Paragraph('7. Repository', styles['Heading2']), Paragraph('Repository sumber: https://github.com/hermanka/quiz-pengupil<br/>Silakan ganti dengan URL fork GitHub Anda setelah push.', styles['BodyText'])]
doc.build(story)
print(out)
